const constants = {
    FETCH_GAME_LISTS_REQUEST: "FETCH_GAME_LISTS_REQUEST",
	CANCEL_FETCHING_GAME_LISTS: "CANCEL_FETCHING_GAME_LISTS",
    FETCH_GAME_LISTS_SUCCESS: "FETCH_GAME_LISTS_SUCCESS",
    FETCH_GAME_LISTS_FAILED: "FETCH_GAME_LISTS_FAILED",
    
    FETCH_GAMES_REQUEST: "FETCH_GAMES",
	CANCEL_FETCHING_GAMES: "CANCEL_FETCHING_GAMES",
    FETCH_GAMES_SUCCESS: "FETCH_GAMES_SUCCESS",
    FETCH_GAMES_FAILED: "FETCH_GAMES_FAILED",

    FETCH_USERS_REQUEST: "FETCH_GAMES",
	CANCEL_FETCHING_USERS: "CANCEL_FETCHING_GAMES",
    FETCH_USERS_SUCCESS: "FETCH_GAMES_SUCCESS",
    FETCH_USERS_FAILED: "FETCH_GAMES_FAILED",

    SET_USER_ADMIN: "SET_USER_ADMIN",
    SET_USER_VERIFITY: "SET_USER_VERIFITY",
    DELETE_USER: "DELETE_USER",

    ADD_REVIEWS: "ADD_REVIEWS",
    FETCH_REVIEWS_REQUEST: "FETCH_REVIEWS",
	CANCEL_FETCHING_REVIEWS: "CANCEL_FETCHING_REVIEWS",
    FETCH_REVIEWS_SUCCESS: "CHANGE_REVIEWS",
    FETCH_REVIEWS_FAILED: "FETCH_GAMES_SUCCESS",

    LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
    LOGOUT_USER: "LOGOUT_USER",

    REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST",
    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",

    FETCH_SEARCH_SUGGESTIONS_REQUEST: "FETCH_SEARCH_SUGGESTIONS_REQUEST",
    FETCH_SEARCH_SUGGESTIONS_SUCCESS: "FETCH_SEARCH_SUGGESTIONS_SUCCESS",
    FETCH_SEARCH_SUGGESTIONS_FAILED: "FETCH_SEARCH_SUGGESTIONS_FAILED",

    SEARCHING: "SEARCHING",
    SEARCH_SUCCESS: "SEARCH_SUCCESS",
    SEARCH_FAILED: "SEARCH_FAILED",

    OPEN_LOGIN_FORM: "OPEN_LOGIN_FORM",
    CLOSE_LOGIN_FORM: "CLOSE_LOGIN_FORM",
    OPEN_REGISTER_FORM: "OPEN_REGISTER_FORM",
    CLOSE_REGISTER_FORM: "CLOSE_REGISTER_FORM",
    OPEN_SETTING_POPOVER: "OPEN_SETTING_POPOVER",
    CLOSE_SETTING_POPOVER: "CLOSE_SETTING_POPOVER",

    FETCH_GAMELIST_DETAILS_REQUEST: "FETCH_GAME_LIST_DETAILS_REQUEST",
    FETCH_GAMELIST_DETAILS_SUCCESS: "FETCH_GAMELIST_DETAILS_SUCCESS",
    FETCH_GAMELIST_DETAILS_FAILED: "FETCH_GAMELIST_DETAILS_FAILED",
    ADD_GAMELIST_REVIEW_REQUEST: "ADD_GAMELIST_REVIEW_REQUEST",
    ADD_GAMELIST_REVIEW_SUCCESS: "ADD_GAMELIST_REVIEW_SUCCESS",
    ADD_GAMELIST_REVIEW_FAILED: "ADD_GAMELIST_REVIEW_FAILED",


    FETCH_GAME_DETAILS_REQUEST: "FETCH_GAME_DETAILS_REQUEST",
    FETCH_GAME_DETAILS_SUCCESS: "FETCH_GAME_DETAILS_SUCCESS",
    FETCH_GAME_DETAILS_FAILED: "FETCH_GAME_DETAILS_FAILED",
    ADD_GAME_REVIEW_REQUEST: "ADD_GAME_REVIEW_REQUEST",
    ADD_GAME_REVIEW_SUCCESS: "ADD_GAME_REVIEW_SUCCESS",
    ADD_GAME_REVIEW_FAILED: "ADD_GAME_REVIEW_FAILED",

    ADD_GAME_LIST_REQUEST: "ADD_GAME_LIST_REQUEST",
    ADD_GAME_LIST_SUCCESS: "ADD_GAME_LIST_SUCCESS",
    ADD_GAME_LIST_FAILED: "ADD_GAME_LIST_FAILED",

    ADD_GAME_TO_ADD_GAMELIST: "ADD_GAME_TO_ADD_GAMELIST",
    REMOVE_GAME_TO_ADD_GAMELIST: "REMOVE_GAME_TO_ADD_GAMELIST",

    FETCH_GAME_SUGGESTIONS_REQUEST: "FETCH_GAME_SUGGESTIONS_REQUEST",
    FETCH_GAME_SUGGESTIONS_SUCCESS: "FETCH_GAME_SUGGESTIONS_SUCCESS",
    FETCH_GAME_SUGGESTIONS_FAILED: "FETCH_GAME_SUGGESTIONS_FAILED",

    ADD_GAME_REQUEST: "ADD_GAME_REQUEST",
    ADD_GAME_SUCCESS: "ADD_GAME_SUCCESS",
    ADD_GAME_FAILED: "ADD_GAME_FAILED",

    ADD_ERROR_MESSAGE: "ADD_ERROR_MESSAGE",
    CLOSE_ERROR_DIALOG: "CLOSE_ERROR_DIALOG",

    REMOVE_GAME_FROM_GAMELIST_REQUEST: "REMOVE_GAME_FROM_GAMELIST_REQUEST",
    REMOVE_GAME_FROM_GAMELIST_SUCCESS: "REMOVE_GAME_FROM_GAMELIST_SUCCESS",
    REMOVE_GAME_FROM_GAMELIST_FAILED: "REMOVE_GAME_FROM_GAMELIST_FAILED",

    ADD_GAME_FROM_GAMELIST_REQUEST: "ADD_GAME_FROM_GAMELIST_REQUEST",
    ADD_GAME_FROM_GAMELIST_SUCCESS: "ADD_GAME_FROM_GAMELIST_SUCCESS",
    ADD_GAME_FROM_GAMELIST_FAILED: "ADD_GAME_FROM_GAMELIST_FAILED",

    UPLOAD_GAME_COVER_REQUEST: "UPLOAD_GAME_COVER_REQUEST",
    UPLOAD_GAME_COVER_SUCCESS: "UPLOAD_GAME_COVER_SUCCESS",
    UPLOAD_GAME_COVER_FAILED: "UPLOAD_GAME_COVER_FAILED",

    UPLOAD_GAME_SCREENSHOT_REQUEST: "UPLOAD_GAME_SCREENSHOT_REQUEST",
    UPLOAD_GAME_SCREENSHOT_SUCCESS: "UPLOAD_GAME_SCREENSHOT_SUCCESS",
    UPLOAD_GAME_SCREENSHOT_FAILED: "UPLOAD_GAME_SCREENSHOT_FAILED",

    UPLOAD_GAMELIST_COVER_REQUEST: "UPLOAD_GAMELIST_COVER_REQUEST",
    UPLOAD_GAMELIST_COVER_SUCCESS: "UPLOAD_GAMELIST_COVER_SUCCESS",
    UPLOAD_GAMELIST_COVER_FAILED: "UPLOAD_GAMELIST_COVER_FAILED",

    UPLOAD_AVATAR_REQUEST: "UPLOAD_AVATAR_REQUEST",
    UPLOAD_AVATAR_SUCCESS: "UPLOAD_AVATAR_SUCCESS",
    UPLOAD_AVATAR_FAILED: "UPLOAD_AVATAR_FAILED",

    INIT_UPLOAD_FILES: "INIT_UPLOAD_FILES",

    FETCH_GAMELISTS_BY_USER_SUCCESS: "FETCH_GAMELISTS_BY_USER_SUCCESS",

    ADD_GAME_TO_GAMELIST_SUCCESS: "ADD_GAME_TO_GAMELIST_SUCCESS",

    OPEN_EDIT_AVATAR: "OPEN_EDIT_AVATAR",
    CLOSE_EDIT_AVATAR: "CLOSE_EDIT_AVATAR",

    SAVE_TEMP_REGISTER: "SAVE_TEMP_REGISTER",
    INIT_TEMP_REGISTER: "INIT_TEMP_REGISTER"
}

export default constants