const constants = {
    FETCH_GAME_LISTS_REQUEST: "FETCH_GAME_LISTS_REQUEST",
	CANCEL_FETCHING_GAME_LISTS: "CANCEL_FETCHING_GAME_LISTS",
    FETCH_GAME_LISTS_SUCCESS: "FETCH_GAME_LISTS_SUCCESS",
    FETCH_GAME_LISTS_FAILED: "FETCH_GAME_LISTS_FAILED",
    
    FETCH_GAMES_REQUEST: "FETCH_GAMES",
	CANCEL_FETCHING_GAMES: "CANCEL_FETCHING_GAMES",
    FETCH_GAMES_SUCCESS: "FETCH_GAMES_SUCCESS",
    FETCH_GAMES_FAILED: "FETCH_GAMES_FAILED",

    FETCH_USERS_REQUEST: "FETCH_GAMES",
	CANCEL_FETCHING_USERS: "CANCEL_FETCHING_GAMES",
    FETCH_USERS_SUCCESS: "FETCH_GAMES_SUCCESS",
    FETCH_USERS_FAILED: "FETCH_GAMES_FAILED",

    ADD_REVIEWS: "ADD_REVIEWS",
    FETCH_REVIEWS_REQUEST: "FETCH_REVIEWS",
	CANCEL_FETCHING_REVIEWS: "CANCEL_FETCHING_REVIEWS",
    FETCH_REVIEWS_SUCCESS: "CHANGE_REVIEWS",
    FETCH_REVIEWS_FAILED: "FETCH_GAMES_SUCCESS",

    LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
    LOGOUT_USER: "LOGOUT_USER",

    FETCH_SEARCH_SUGGESTIONS_REQUEST: "FETCH_SEARCH_SUGGESTIONS_REQUEST",
    FETCH_SEARCH_SUGGESTIONS_SUCCESS: "FETCH_SEARCH_SUGGESTIONS_SUCCESS",
    FETCH_SEARCH_SUGGESTIONS_FAILED: "FETCH_SEARCH_SUGGESTIONS_FAILED",

    SEARCHING: "SEARCHING",
    SEARCH_SUCCESS: "SEARCH_SUCCESS",
    SEARCH_FAILED: "SEARCH_FAILED",

    OPEN_LOGIN_FORM: "OPEN_LOGIN_FORM",
    CLOSE_LOGIN_FORM: "CLOSE_LOGIN_FORM",
    OPEN_REGISTER_FORM: "OPEN_REGISTER_FORM",
    CLOSE_REGISTER_FORM: "CLOSE_REGISTER_FORM",
    OPEN_SETTING_POPOVER: "OPEN_SETTING_POPOVER",
    CLOSE_SETTING_POPOVER: "CLOSE_SETTING_POPOVER",

    FETCH_GAMELIST_DETAILS_REQUEST: "FETCH_GAME_LIST_DETAILS_REQUEST",
    FETCH_GAMELIST_DETAILS_SUCCESS: "FETCH_GAMELIST_DETAILS_SUCCESS",
    FETCH_GAMELIST_DETAILS_FAILED: "FETCH_GAMELIST_DETAILS_FAILED",
    ADD_GAMELIST_REVIEW_REQUEST: "ADD_GAMELIST_REVIEW_REQUEST",
    ADD_GAMELIST_REVIEW_SUCCESS: "ADD_GAMELIST_REVIEW_SUCCESS",
    ADD_GAMELIST_REVIEW_FAILED: "ADD_GAMELIST_REVIEW_FAILED",


    FETCH_GAME_DETAILS_REQUEST: "FETCH_GAME_DETAILS_REQUEST",
    FETCH_GAME_DETAILS_SUCCESS: "FETCH_GAME_DETAILS_SUCCESS",
    FETCH_GAME_DETAILS_FAILED: "FETCH_GAME_DETAILS_FAILED",
    ADD_GAME_REVIEW_REQUEST: "ADD_GAME_REVIEW_REQUEST",
    ADD_GAME_REVIEW_SUCCESS: "ADD_GAME_REVIEW_SUCCESS",
    ADD_GAME_REVIEW_FAILED: "ADD_GAME_REVIEW_FAILED",

    ADD_GAME_LIST_REQUEST: "ADD_GAME_LIST_REQUEST",
    ADD_GAME_LIST_SUCCESS: "ADD_GAME_LIST_SUCCESS",
    ADD_GAME_LIST_FAILED: "ADD_GAME_LIST_FAILED",

    ADD_GAME_TO_ADD_GAMELIST: "ADD_GAME_TO_ADD_GAMELIST",
    REMOVE_GAME_TO_ADD_GAMELIST: "REMOVE_GAME_TO_ADD_GAMELIST",

    FETCH_GAME_SUGGESTIONS_REQUEST: "FETCH_GAME_SUGGESTIONS_REQUEST",
    FETCH_GAME_SUGGESTIONS_SUCCESS: "FETCH_GAME_SUGGESTIONS_SUCCESS",
    FETCH_GAME_SUGGESTIONS_FAILED: "FETCH_GAME_SUGGESTIONS_FAILED",

    ADD_GAME_REQUEST: "ADD_GAME_REQUEST",
    ADD_GAME_SUCCESS: "ADD_GAME_SUCCESS",
    ADD_GAME_FAILED: "ADD_GAME_FAILED"

}

export default constants