const constants = {
    FETCH_GAME_LISTS_REQUEST: "FETCH_GAME_LISTS_REQUEST",
	CANCEL_FETCHING_GAME_LISTS: "CANCEL_FETCHING_GAME_LISTS",
    FETCH_GAME_LISTS_SUCCESS: "FETCH_GAME_LISTS_SUCCESS",
    FETCH_GAME_LISTS_FAILED: "FETCH_GAME_LISTS_FAILED",
    
    FETCH_GAMES_REQUEST: "FETCH_GAMES",
	CANCEL_FETCHING_GAMES: "CANCEL_FETCHING_GAMES",
    FETCH_GAMES_SUCCESS: "FETCH_GAMES_SUCCESS",
    FETCH_GAMES_FAILED: "FETCH_GAMES_FAILED",

    FETCH_USERS_REQUEST: "FETCH_GAMES",
	CANCEL_FETCHING_USERS: "CANCEL_FETCHING_GAMES",
    FETCH_USERS_SUCCESS: "FETCH_GAMES_SUCCESS",
    FETCH_USERS_FAILED: "FETCH_GAMES_FAILED",

    ADD_REVIEWS: "ADD_REVIEWS",
    FETCH_REVIEWS_REQUEST: "FETCH_REVIEWS",
	CANCEL_FETCHING_REVIEWS: "CANCEL_FETCHING_REVIEWS",
    FETCH_REVIEWS_SUCCESS: "CHANGE_REVIEWS",
    FETCH_REVIEWS_FAILED: "FETCH_GAMES_SUCCESS",

    LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
    LOGOUT_USER: "LOGOUT_USER",

    FETCH_SEARCH_SUGGESTIONS_REQUEST: "FETCH_SEARCH_SUGGESTIONS_REQUEST",
    FETCH_SEARCH_SUGGESTIONS_SUCCESS: "FETCH_SEARCH_SUGGESTIONS_SUCCESS",
    FETCH_SEARCH_SUGGESTIONS_FAILED: "FETCH_SEARCH_SUGGESTIONS_FAILED",

    UPDATE_SEARCH_TEXT: "UPDATE_SEARCH_TEXT"
}

export default constants