const constants = {
    FETCH_GAME_LISTS: "FETCH_GAME_LISTS",
	CANCEL_FETCHING_GAME_LISTS: "CANCEL_FETCHING_GAME_LISTS",
    CHANGE_GAME_LISTS: "CHANGE_GAME_LISTS",
    ADD_GAME_LISTS: "ADD_GAME_LISTS",
    
    FETCH_GAMES: "FETCH_GAMES",
	CANCEL_FETCHING_GAMES: "CANCEL_FETCHING_GAMES",
    CHANGE_GAMES: "CHANGE_GAMES",
    ADD_GAMES: "ADD_GAMES",

    ADD_REVIEWS: "ADD_REVIEWS",
    FETCH_REVIEWS: "FETCH_REVIEWS",
	CANCEL_FETCHING_REVIEWS: "CANCEL_FETCHING_REVIEWS",
    CHANGE_REVIEWS: "CHANGE_REVIEWS",

}

export default constants